# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.myfaces.tobago:*"
        versions:
          - ">= 5.0.0"
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions:
          - ">= 4.0.0"
      - dependency-name: "org.eclipse.jetty:jetty-maven-plugin"
        versions:
          - ">= 10.0.0"
      - dependency-name: "org.apache.myfaces.core:*"
        versions:
          - ">= 2.1.0"
      - dependency-name: "org.jboss.resteasy:*"
        versions:
          - ">= 5.0.0.Final"
